<a href="https://colab.research.google.com/github/CodingSideUp/Deep-learning/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
!wget https://gitlab.com/andras.simonyi/10_days_AI_training_data/raw/65de5908dccf120762b305238e02610a8c18a3f9/titanic_train.csv

--2024-12-14 23:01:07--  https://gitlab.com/andras.simonyi/10_days_AI_training_data/raw/65de5908dccf120762b305238e02610a8c18a3f9/titanic_train.csv
Resolving gitlab.com (gitlab.com)... 172.65.251.78, 2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61194 (60K) [text/plain]
Saving to: ‘titanic_train.csv.1’

titanic_train.csv.1 100%[===================>]  59.76K  --.-KB/s    in 0.02s

2024-12-14 23:01:07 (2.73 MB/s) - ‘titanic_train.csv.1’ saved [61194/61194]

In [19]:
import pandas as pd

df = pd.read_csv("titanic_train.csv")

In [20]:
print("shape:", df.shape)

shape: (891, 12)

In [21]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [22]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [23]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [24]:
columns_to_drop = ["Cabin", "Ticket", "PassengerId", "Name"]
df = df.drop(columns=columns_to_drop)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [25]:
import numpy as np
age_mean = df.Age.mean()
replacements = {"Sex": {"male": 1, "female":0}, "Age": {np.NaN: age_mean}}
df.replace(replacements, inplace=True)
df.head()

<ipython-input-25-fb80f9842efc>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(replacements, inplace=True)

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    1  22.0      1      0   7.2500        S
1         1       1    0  38.0      1      0  71.2833        C
2         1       3    0  26.0      0      0   7.9250        S
3         1       1    0  35.0      1      0  53.1000        S
4         0       3    1  35.0      0      0   8.0500        S

In [26]:
print("Length before dropping:", len(df))
df.dropna(inplace=True)
df.reset_index()
print("Length after dropping:", len(df))

Length before dropping: 891
Length after dropping: 889

In [27]:
df = pd.get_dummies(df)
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,22.0,1,0,7.2500,False,False,True
1,1,1,0,38.0,1,0,71.2833,True,False,False
2,1,3,0,26.0,0,0,7.9250,False,False,True
3,1,1,0,35.0,1,0,53.1000,False,False,True
4,0,3,1,35.0,0,0,8.0500,False,False,True

In [28]:

from sklearn.model_selection import train_test_split

df_train, df_valid = train_test_split(df, test_size=0.1)

X_train = df_train.drop(columns=["Survived"])
y_train = df_train["Survived"]

X_valid = df_valid.drop(columns=["Survived"])
y_valid = df_valid["Survived"]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_valid shape:", X_valid.shape)
print("y_valid shape:", y_valid.shape)

X_train shape: (800, 9)
y_train shape: (800,)
X_valid shape: (89, 9)
y_valid shape: (89,)

In [29]:
import numpy as np

class Perceptron:
   def step_func(self, z):
      """Activation function: Step function"""
      return np.where(z >= 0, 1, 0)

   def fit(self, X, y, rate=0.001, epoch=500):
      """Fit training data
      X : Training vectors, X.shape : [#samples, #features]
      y : Target values, y.shape : [#samples]
      """
      n_samples, n_features = X.shape

      # Initialize weights and bias
      self.weight = np.zeros(n_features)
      self.bias = 0

      for e in range(epoch):
         n_miss = 0  # Number of misclassifications

         # Random shuffle the data
         perm = np.random.permutation(n_samples)

         for xi, target in zip(X[perm], y[perm]):
            # Calculate y_hat (prediction using step function)
            y_hat = self.step_func(np.dot(xi, self.weight) + self.bias)

            # Calculate delta W if target != y_hat (misclassification)
            if target != y_hat:
               delta_w = rate * (target - y_hat)  # Change in weights

               # Update weight and bias if misclassification occurs
               self.weight += delta_w * xi
               self.bias += delta_w

               # Increase misclassifications number if applied
               n_miss += 1

         # Print the number of misclassifications every 50 epochs
         if e % 50 == 0:
            print(f"Epoch {e} - Wrong prediction: {n_miss}")

      print("Finished training. Lost:", n_miss)

   def predict(self, X):
      """Return class label after unit step"""
      return self.step_func(np.dot(X, self.weight) + self.bias)

In [32]:
# Ensure numeric types
X_train = X_train.astype(np.float64)
y_train = y_train.astype(np.int64)

p = Perceptron()
p.fit(X_train.to_numpy(), y_train.to_numpy(), 0.001, 500)

Epoch 0 - Wrong prediction: 318
Epoch 50 - Wrong prediction: 244
Epoch 100 - Wrong prediction: 222
Epoch 150 - Wrong prediction: 225
Epoch 200 - Wrong prediction: 238
Epoch 250 - Wrong prediction: 242
Epoch 300 - Wrong prediction: 228
Epoch 350 - Wrong prediction: 229
Epoch 400 - Wrong prediction: 229
Epoch 450 - Wrong prediction: 232
Finished training. Lost: 218